// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lrdshbnpkjdrydfcjcnv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxyZHNoYm5wa2pkcnlkZmNqY252Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY1OTQ1NjcsImV4cCI6MjA3MjE3MDU2N30.J8yNnzBOIfZo9YBCr2qk4vDtCNXo_b_b6jCqHLV2Huk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});